# config/chewy.yml
# separate environment configs
test:
  host: <%= ENV.fetch("ELASTICSEARCH_URL") { "localhost:9250" } %>
  prefix: 'test'
development:
  host: <%= ENV.fetch("ELASTICSEARCH_URL") { "10.116.41.19:9200" } %>
production:
  host: <%= ENV.fetch("ELASTICSEARCH_URL") { "localhost:9200" } %>
